In [6]:
import numpy as np

WINDOW_WIDTH = 1000  # size of window's width in pixels
WINDOW_HEIGHT = 600  # size of windows' height in pixels
CELL_SIZE = 200  # size of cell height & width in pixels
GAP_SIZE = 1  # size of gap between cells in pixels
CELL_COLUMN = 3  # number of columns of cells
CELL_ROW = 2  # number of rows of cells
NUM_CELL = CELL_COLUMN * CELL_ROW  # num of cells
LEFT_MARGIN = int((WINDOW_WIDTH - (CELL_COLUMN * (CELL_SIZE + GAP_SIZE))) / 2)
RIGHT_MARGIN = int(WINDOW_WIDTH - LEFT_MARGIN)
TOP_MARGIN = int((WINDOW_HEIGHT - (CELL_ROW * (CELL_SIZE + GAP_SIZE))) / 2)
BOTTOM_MARGIN = int(WINDOW_HEIGHT - TOP_MARGIN)
NUM_USER = 20
RESOURCE_LIST = [10, 8, 6, 10, 8, 6, 6, 10, 7, 10, 5, 7, 4, 8, 9, 5, 6, 5, 9]

In [7]:
def init_users():
    """
        initialize user. every user consists of 4 params:
        (1) loc_x(center) (2) loc_y(center) (3) which cell user is in (4) user mobility type
        user mobility type is divided into 3 categories: low, medium and high. Low mobility users takes 70% of all,
        while medium and high takes 20% and 10%.
        :return: user: (1) loc_x(center) (2) loc_y(center) (3) which cell user is in (4) user mobility type
        """
    loc_x = np.random.randint(LEFT_MARGIN, RIGHT_MARGIN, size=NUM_USER)
    loc_y = np.random.randint(TOP_MARGIN, BOTTOM_MARGIN, size=NUM_USER)
    cell_id = which_cell(loc_x=loc_x, loc_y=loc_y)
    mobility_type = np.random.choice([1,5,10], size=NUM_USER, p=[0.7, 0.2, 0.1]) # low(70%), medium(20%), high(10%)
    users = np.vstack((loc_x, loc_y, cell_id, mobility_type))
    return users.T

def which_cell(loc_x, loc_y):
    """
    calculate which cell the user is in
    :param loc_x:
    :param loc_y:
    :return: cell_id
    """
    column = np.ceil((loc_x - LEFT_MARGIN) / CELL_SIZE)
    row = np.ceil((loc_y - TOP_MARGIN) / CELL_SIZE)
    cell_id = (row - 1) * CELL_COLUMN + column
    return cell_id

In [8]:
users = init_users()
print(users)

[[ 346.  137.    1.    1.]
 [ 718.  445.    6.    1.]
 [ 704.  148.    3.    5.]
 [ 385.  387.    4.    1.]
 [ 384.  485.    4.    1.]
 [ 566.  499.    5.    1.]
 [ 624.  114.    3.    5.]
 [ 252.  178.    1.    1.]
 [ 439.  310.    5.    1.]
 [ 733.  253.    3.    1.]
 [ 627.  136.    3.    1.]
 [ 229.  394.    4.    1.]
 [ 530.  467.    5.   10.]
 [ 578.  400.    5.    1.]
 [ 207.  414.    4.    5.]
 [ 718.  392.    6.    1.]
 [ 681.  235.    3.    1.]
 [ 687.  265.    3.    5.]
 [ 573.  153.    2.    1.]
 [ 599.  311.    6.    1.]]


In [9]:
def init_cells():
    """
    initialize cell list, every cell in the lists consists of 5 params:
    (1)loc_x(left) (2)loc_y(top) (3)NO. (4)PRB number (5)load
    :return: cell_list: (1)loc_x(left) (2)loc_y(top) (3)NO. (4)PRB number (5)load
    """
    # cell location
    flatten_x = np.tile(np.arange(CELL_COLUMN), CELL_ROW)
    flatten_y = np.repeat(np.arange(CELL_ROW), CELL_COLUMN)
    cell_x = flatten_x * (CELL_SIZE + GAP_SIZE) + LEFT_MARGIN
    cell_y = flatten_y * (CELL_SIZE + GAP_SIZE) + TOP_MARGIN
    
    cell_id = np.arange(NUM_CELL)
    cell_PRB = np.array(RESOURCE_LIST[:NUM_CELL])
    cell_load = np.zeros(NUM_CELL)
    
    cells = np.vstack((cell_x, cell_y, cell_id, cell_PRB, cell_load))
    return cells.T

cells = init_cells()
print(cells)

[[ 198.   99.    0.   10.    0.]
 [ 399.   99.    1.    8.    0.]
 [ 600.   99.    2.    6.    0.]
 [ 198.  300.    3.   10.    0.]
 [ 399.  300.    4.    8.    0.]
 [ 600.  300.    5.    6.    0.]]


In [13]:
def user_mobility(users):
    """
    user mobility func update users' location in every frame. mobility range comes from user mobility type. Meanwhile,
    user should only move in the cell range, restricted by the MARGIN.
    :param user_list: (1) loc_x(center) (2) loc_y(center) (3) which cell user is in (4) user mobility type
    :return: new_user_list: (1) loc_x(center) (2) loc_y(center) (3) which cell user is in (4) user mobility type
    """
    mobility = users[:,3]
    move_x = mobility*np.random.uniform(-1,1,size=len(mobility))
    print(move_x)
    move_y = mobility*np.random.uniform(-1,1,size=len(mobility))
    user_x = users[:,0] + move_x
    user_y = users[:,1] + move_y
    user_x = np.clip(user_x, LEFT_MARGIN + 4, RIGHT_MARGIN - 4)
    user_y = np.clip(user_y, TOP_MARGIN + 4, BOTTOM_MARGIN - 4)
    return user_x, user_y

user_x, user_y = user_mobility(users)
print(user_x, user_y)

[  1.   1.   5.   1.   1.   1.   5.   1.   1.   1.   1.   1.  10.   1.   5.
   1.   1.   5.   1.   1.]
[ 0.27861974  0.69707282 -0.12983559 -0.75253292  0.38056648  0.98697743
 -0.78673886  0.77677103 -0.31962717  0.92735227 -0.4017204  -0.03411587
 -0.90735374  0.31488965 -0.16975477  0.09741551  0.35272702  0.36237309
 -0.16082193  0.78058962]
[-0.5491273   0.35284397 -2.17700623 -0.93103989  0.74426309 -0.61826643
 -2.26660149 -0.8564505  -0.29475454  0.92536152  0.60251163 -0.70459314
 -9.26568804 -0.4359116  -2.43774625 -0.93398479  0.05147365  3.13963182
 -0.33291547 -0.88497868]
[ 345.4508727   718.35284397  701.82299377  384.06896011  384.74426309
  565.38173357  621.73339851  251.1435495   438.70524546  733.92536152
  627.60251163  228.29540686  520.73431196  577.5640884   204.56225375
  717.06601521  681.05147365  690.13963182  572.66708453  598.11502132] [ 137.64378302  444.78505648  143.01465328  386.85734717  485.54934627
  497.          114.80618821  177.37609663  309.526

In [6]:
from collections import Counter

def update_load(cells, users):
    """
    calculate cell load according to the sum of users in its range.
    :param cell_list:
    :param user_list:
    :return:
    """
    # count users in each cell
    user_in = users[:,2]-1
    print(user_in)
    user_count =  Counter(user_in).most_common()
    print(user_count)
    
    # update the load of each cell in cell list
    for item in user_count:
        cells[item[0]][4] = item[1]
    return cells

print(cells)
cells = update_load(cells, users)
print(cells)

[[ 198.   99.    0.   10.    0.]
 [ 399.   99.    1.    8.    0.]
 [ 600.   99.    2.    6.    0.]
 [ 198.  300.    3.   10.    0.]
 [ 399.  300.    4.    8.    0.]
 [ 600.  300.    5.    6.    0.]]
[ 3.  4.  4.  0.  3.  2.  0.  5.  5.  2.  3.  1.  5.  5.  1.  2.  2.  3.
  3.  3.]
[(3.0, 6), (2.0, 4), (5.0, 4), (0.0, 2), (1.0, 2), (4.0, 2)]
[[ 198.   99.    0.   10.    2.]
 [ 399.   99.    1.    8.    2.]
 [ 600.   99.    2.    6.    4.]
 [ 198.  300.    3.   10.    6.]
 [ 399.  300.    4.    8.    2.]
 [ 600.  300.    5.    6.    4.]]


/Users/Dijkstraaaaa/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:18: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [7]:
def cal_reward(cells):
    reward = 0
    resource = cells[:,3]
    load = cells[:,4]
    normal = resource>load
    reward = np.sum(normal.astype(int)-1)
    return reward

reward = cal_reward(cells)
print(reward)

0


In [1]:
import pygame
import sys
import random
import numpy as np
from pygame.locals import *
from colour import Color
from collections import Counter


# frame params
FPS = 3  # frames per second, the general speed of the program
WINDOW_WIDTH = 1000  # size of window's width in pixels
WINDOW_HEIGHT = 600  # size of windows' height in pixels
CELL_SIZE = 200  # size of cell height & width in pixels
GAP_SIZE = 1  # size of gap between cells in pixels
CELL_COLUMN = 3  # number of columns of cells
CELL_ROW = 2  # number of rows of cells
NUM_CELL = CELL_COLUMN * CELL_ROW  # num of cells
LEFT_MARGIN = int((WINDOW_WIDTH - (CELL_COLUMN * (CELL_SIZE + GAP_SIZE))) / 2)
RIGHT_MARGIN = int(WINDOW_WIDTH - LEFT_MARGIN)
TOP_MARGIN = int((WINDOW_HEIGHT - (CELL_ROW * (CELL_SIZE + GAP_SIZE))) / 2)
BOTTOM_MARGIN = int(WINDOW_HEIGHT - TOP_MARGIN)
NUM_USER = 20
white = Color("white")
COLOR_LIST = list(white.range_to(Color("black"), 15))
RESOURCE_LIST = [10, 8, 6, 10, 8, 6, 6, 10, 7, 10, 5, 7, 4, 8, 9, 5, 6, 5, 9]

# RGB
GRAY = (100, 100, 100)
NAVY_BLUE = (60, 60, 100)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 128, 0)
PURPLE = (255, 0, 255)
CYAN = (0, 255, 255)
BG_COLOR = NAVY_BLUE
CELL_COLOR = WHITE
pygame.init()
FPS_CLOCK = pygame.time.Clock()
DISPLAY_SURF = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))
pygame.display.set_caption('MLB System Model')


class SystemModel:
    def __init__(self):
        self.users = self.init_users()
        self.cells = self.init_cells()

    def init_users(self):
        """
        initialize user. every user consists of 4 params:
        (1) loc_x(center) (2) loc_y(center) (3) which cell user is in (4) user mobility type
        user mobility type is divided into 3 categories: low, medium and high. Low mobility users takes 70% of all,
        while medium and high takes 20% and 10%.
        :return: user: (1) loc_x(center) (2) loc_y(center) (3) which cell user is in (4) user mobility type
         """
        user_x = np.random.randint(LEFT_MARGIN, RIGHT_MARGIN, size=NUM_USER)
        user_y = np.random.randint(TOP_MARGIN, BOTTOM_MARGIN, size=NUM_USER)
        cell_id = self.which_cell(loc_x=user_x, loc_y=user_y)
        mobility_type = np.random.choice(3, size=NUM_USER, p=[0.7, 0.2, 0.1])  # low(70%), medium(20%), high(10%)
        users = np.vstack((user_x, user_y, cell_id, mobility_type))
        return users.T

    @staticmethod
    def init_cells():
        """
        initialize cell list, every cell in the lists consists of 5 params:
        (1)loc_x(left) (2)loc_y(top) (3)NO. (4)PRB number (5)load
        :return: cell_list: (1)loc_x(left) (2)loc_y(top) (3)NO. (4)PRB number (5)load
        """
        # cell location
        flatten_x = np.tile(np.arange(CELL_COLUMN), CELL_ROW)
        flatten_y = np.repeat(np.arange(CELL_ROW), CELL_COLUMN)
        cell_x = flatten_x * (CELL_SIZE + GAP_SIZE) + LEFT_MARGIN
        cell_y = flatten_y * (CELL_SIZE + GAP_SIZE) + TOP_MARGIN

        cell_id = np.arange(NUM_CELL)
        cell_PRB = np.array(RESOURCE_LIST[:NUM_CELL])
        cell_load = np.zeros(NUM_CELL)

        cells = np.vstack((cell_x, cell_y, cell_id, cell_PRB, cell_load))
        return cells.T

    @staticmethod
    def which_cell(loc_x, loc_y):
        """
        calculate which cell the user is in
        :param loc_x:
        :param loc_y:
        :return: cell_id
        """
        column = np.ceil((loc_x - LEFT_MARGIN) / CELL_SIZE)
        row = np.ceil((loc_y - TOP_MARGIN) / CELL_SIZE)
        cell_id = (row - 1) * CELL_COLUMN + column
        return cell_id

    def move_user(self):
        """
        user mobility func update users' location in every frame. mobility range comes from user mobility type. Meanwhile,
        user should only move in the cell range, restricted by the MARGIN.
        """
        mobility = self.users[:, 3]

        move_x = mobility * np.random.uniform(-1, 1, size=len(mobility))
        user_x = self.users[:, 0] + move_x  # update loc according to user mobility type
        self.users[:, 0] = np.clip(user_x, LEFT_MARGIN + 4, RIGHT_MARGIN - 4)  # restrict user loc in the cell range

        move_y = mobility * np.random.uniform(-1, 1, size=len(mobility))
        user_y = self.users[:, 1] + move_y  # update loc according to user mobility type
        self.users[:, 1] = np.clip(user_y, TOP_MARGIN + 4, BOTTOM_MARGIN - 4)  # restrict user loc in the cell range

    def update_load(self):
        """
        calculate cell load according to the sum of users in its range.
        """
        # count users in each cell
        user_in = self.users[:, 2] - 1
        user_count = Counter(user_in).most_common()
        # update the load of each cell in cell list
        for item in user_count:
            print(item[0])
            self.cells[item[0]][4] = item[1]

    def get_reward(self):
        resource = self.cells[:, 3]
        load = self.cells[:, 4]
        normal = resource > load
        reward = np.sum(normal.astype(int) - 1)
        return reward

    def draw_cells(self):
        """
        draw cell square and paint color according to cell location and outrage ratio. outrage ratio denotes the balance
        between cell resources and cell load. Color in each cell is chosen according to the outrage ratio. Dark color means
        the cell is high-burden, opposite otherwise. Black color means ratio is lager than 1, meaning that cell is outrage.
        :param cell_list: (1)loc_x(left) (2)loc_y(top) (3)NO. (4)PRB number (5)load
        :return:
        """
        outrage_ratio = [x[4] / x[3] for x in self.cells]
        # print(cell_list)
        # print(outrage_ratio)
        outrage_ratio = [min(x, 1) for x in outrage_ratio]  # larger than 1 is outrage, use black color directly
        # print_list = [round(x, 2) for x in outrage_ratio]
        # print(print_list)
        color_index = [int(x * len(COLOR_LIST)) for x in outrage_ratio]
        for cell in self.cells:
            this_color_index = color_index[int(cell[2] - 1)]
            this_cell_color = [i * 255 for i in list(COLOR_LIST[this_color_index - 1].rgb)]
            pygame.draw.rect(DISPLAY_SURF, this_cell_color, (cell[0], cell[1], CELL_SIZE, CELL_SIZE))

    def draw_users(self):
        """
        draw user circle according to their center postition
        :param user_list: (1) loc_x(center) (2) loc_y(center)
        :return:
        """
        for user in self.users:
            pygame.draw.circle(DISPLAY_SURF, RED, (int(user[0]), int(user[1])), 2)

    def frame_step(self, input_action):
        # update PRB according to actions
        for i in range(NUM_CELL):
            # take the PRB from cell j to i
            cell_to_take = input_action[i]
            self.cells[i][3] += 1
            self.cells[cell_to_take][3] -= 1
        print(self.cells)

        # update system states
        self.move_user()
        self.update_load()
        reward = self.get_reward()

        # draw frame
        DISPLAY_SURF.fill(BG_COLOR)
        self.draw_cells()
        self.draw_users()
        return reward

In [2]:
items = range(6)
random_action = random.sample(items, len(items))
print(random_action)

[3, 1, 2, 0, 5, 4]


In [3]:
system_model = SystemModel()

In [4]:
reward = system_model.frame_step(random_action)
print(reward)

[[ 198.   99.    0.   10.    0.]
 [ 399.   99.    1.    8.    0.]
 [ 600.   99.    2.    6.    0.]
 [ 198.  300.    3.   10.    0.]
 [ 399.  300.    4.    8.    0.]
 [ 600.  300.    5.    6.    0.]]
2.0
5.0
0.0
1.0
3.0
4.0
-1


/Users/Dijkstraaaaa/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:126: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [13]:
import numpy as np
print(np.random.randint(4))

1


In [14]:
aa = [0,1,2]

In [16]:
print(aa[2:])

[2]


In [21]:
aa = np.zeros(4, dtype = int)
aa[2] = 1
aa = aa.reshape(2,2)
print(aa)

[[0 0]
 [1 0]]
